### ISSUE TITLE
Errors return status code 200

### ISSUE THREAD

**Issue by felipe-soren** [IsmaelNascimento/web_crawler_mimi#4]
some errors like invalid url reuturns status code 200
![error](https://user-images.githubusercontent.com/30413876/74611255-d5e60100-50d8-11ea-9683-64bfc04fdc05.png)

**Comment by IsmaelNascimento** [comment]
Problem fixed with PR(https://github.com/IsmaelNascimento/web_crawler_mimi/pull/5)
